### ISSUE TITLE
Signout link redirection

### ISSUE THREAD

**Issue by MorganBergen** [MorganBergen/clarity#15]
#  `./client/src/components/Questionnaire.js`

The button here in line 223 is not currently functional.

```JavaScript
line 222  <div className="header-right">
line 223      <Button variant="secondary" className="header-button">Logout</Button>
line 224  </div>
```

Using the `navigate('/PATH');` function can you enable the button when activated (click on) will redirect to the login page of the application?

The path you need is provided in the `./client/src/App.js`

```JavaScript
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import { Provider } from 'react-redux';
import store from './redux/store';
import Dashboard from './components/Dashboard';
import MainDashboard from './components/MainDashboard';
import Login from './components/Login';
import Register from './components/Register';
import ForgotPassword from './components/ForgotPassword';
import EmailVerification from './components/EmailVerification';
import Analysis from './components/Analysis';
import Settings from './components/Settings';
import Logging from './components/Logging';
import Reports from './components/Reports';
import { UserProvider } from './context/UserContext';

function App() {
  return (
    <Provider store={store}>
      <UserProvider>
        <Router>
          <Routes>
            <Route path="/" element={<Login />} />
            <Route path="/register" element={<Register />} />
            <Route path="/forgot-password" element={<ForgotPassword />} />
            <Route path="/dashboard" element={<Dashboard />} />
            <Route path="/MainDashboard" element={<MainDashboard />} />
            <Route path="/_/#/auth/confirm-verification/:token" element={<EmailVerification />} />
            <Route path="/Analysis" element={<Analysis />} />
            <Route path="/Settings" element={<Settings />} />
            <Route path="/Logging" element={<Logging />} />
            <Route path="/Reports" element={<Reports />} />
          </Routes>
        </Router>
      </UserProvider>
    </Provider>
  );
}

export default App;
```

**Comment by MorganBergen** [comment]
Replace line `223` with the following @BlazingEmerald 

```JavaScript
 <Button
        variant="secondary"
        className="header-button"
        onClick={() => navigate('/')}
      >
        Logout
      </Button>
```

**Comment by BlazingEmerald** [comment]
@BlazingEmerald ➜ /workspaces/clarity/server (15-signout-link-redirection) $ npm run dev


> clarity-backend@1.0.0 dev
> nodemon server.js

[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node server.js`
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (node:net:1904:16)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at Function.listen (/workspaces/clarity/server/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/workspaces/clarity/server/server.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1940:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 5001
}

Node.js v20.17.0
[nodemon] app crashed - waiting for file changes before starting...
^A

**Comment by BlazingEmerald** [comment]
@BlazingEmerald ➜ /workspaces/clarity/server (15-signout-link-redirection) $ lsof -i :5001
COMMAND   PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    18036 codespace   22u  IPv6 217838      0t0  TCP *:5001 (LISTEN)

**Comment by MorganBergen** [comment]
port 5001 is occupied already run the following commands to open up the port

`lsof -i :5001`

`kill -9 PID`
