### ISSUE TITLE
test

### ISSUE THREAD

**Issue by MorganBergen** [MorganBergen/clarity#16]
#!/bin/bash

echo "System Information:"
echo "-------------------"
echo "OS Version: $(sw_vers -productVersion)"
echo "Hostname: $(hostname)"
echo "Kernel: $(uname -r)"
echo "Uptime: $(uptime | awk -F', ' '{print $1}')"
echo "Packages Installed (Homebrew): $(brew list | wc -l)"
echo "Shell: $SHELL"
echo "Resolution: $(system_profiler SPDisplaysDataType | grep Resolution | awk '{print $2 "x" $4}')"
echo "CPU: $(sysctl -n machdep.cpu.brand_string)"
echo "Free Memory (MB): $(vm_stat | grep free | awk '{print $3 * 4096 / 1024 / 1024}')"
echo "Battery: $(pmset -g batt | grep -Eo "\d+%")"

**Comment by BlazingEmerald** [comment]
checksums.txt
734 Bytes 2024-10-08T17:34:52Z
pocketbase_0.23.0-rc3_darwin_amd64.zip
14.1 MB 2024-10-08T17:34:52Z
pocketbase_0.23.0-rc3_darwin_arm64.zip
13.5 MB 2024-10-08T17:34:50Z
pocketbase_0.23.0-rc3_linux_amd64.zip
13.9 MB 2024-10-08T17:34:50Z
pocketbase_0.23.0-rc3_linux_arm64.zip
12.9 MB 2024-10-08T17:34:50Z
pocketbase_0.23.0-rc3_linux_armv7.zip
12.9 MB 2024-10-08T17:34:50Z
pocketbase_0.23.0-rc3_windows_amd64.zip
14.2 MB 2024-10-08T17:34:52Z
pocketbase_0.23.0-rc3_windows_arm64.zip
13 MB 2024-10-08T17:34:52Z
Source code (zip)
2024-10-08T16:57:52Z
Source code (tar.gz)

**Comment by BlazingEmerald** [comment]
echo host name `6.5.0-1025-azure`

**Comment by BlazingEmerald** [comment]
`wget https://github.com/pocketbase/pocketbase/releases/download/v0.23.0-rc3/pocketbase_0.23.0-rc3_linux_amd64.zip`

`unzip pocketbase_0.23.0-rc3_linux_amd64.zip`

`chmod +x pocketbase`

`./pocketbase serve`
