### ISSUE TITLE
register to open house DUE NOV 8

### ISSUE THREAD

**Issue by MorganBergen** [MorganBergen/clarity#60]
[fill out form here](https://wichitastate.co1.qualtrics.com/jfe/form/SV_0p0aV2HI2o2OmRE)

1.  Project Title
2.  Brief Project Description
3.  Team Name
4.  Team Captain Name
5.  Team Captain Email address
6.  Team Captain Phone Number
7.  Team Members' Names & Email - List the names and emails for all team members including the team captain. (Format: First Name Last Name, email address; First Name Last Name, email address)
8.  Your Team Member Department(s)
9.  Is this your final semester with this project, or will it continue next semester? 
10.  Faculty Advisor or Mentor
11.  Did you have an Industry or Community Sponsor?

**Comment by BlazingEmerald** [comment]
1. Clarity
2.	Clarity is a web and mobile application that leverages image recognition and machine learning to analyze the nutritional content of food and comprehensive health management tool. Designed to empower users with real time dietary insights and transform the way individuals manage their chronic conditions, nutrition, and overall health.
3.	Clarity
4.	Morgan Bergen
5.	[mxbergen@shockers.wichita.edu](mailto:mxbergen@shockers.wichita.edu)
6.	316-806-3999
7.	Morgan Bergen, [mxbergen@shockers.wichita.edu](mailto:mxbergen@shockers.wichita.edu); Jason Heitman, [p468g752@wichita.edu](mailto:p468g752@wichita.edu); Christal Shaner, [crshaner@shockers.wichita.edu](mailto:crshaner@shockers.wichita.edu);
8.	Department: Computer Science
9.	Project will continue next semester
10.	Professor Huabo Lu
11.	No
*if anyone has a problem with this, plz let me know. if not I can submit it

**Comment by MorganBergen** [comment]
Looks good to me! @ChristalShaner what do you think?
