### ISSUE TITLE
Demo 3 presentation

### ISSUE THREAD

**Issue by MorganBergen** [MorganBergen/clarity#66]
due 11/21/24

Assignment Instructions
(Group work)

Please upload a .pptx file for your Demo 3 presentation. 

Note that this document will be archived, so the following formality is required: 
Cover page to include project title and group member names.
A few slides (2- 4) to cover your new work since Demo 2.
GitHub pages (2 - 4) to cover main commits made since Demo 2.
Screenshot pages (2- 4) to show new features/maintenance in Demo 3. 
EOH plan pages (2 - 4). I have ordered some trifolds, so what would you like to post on the trifold? 
Conclusion pages (2 - 4). Please conclude this semester's work. 
Plan pages (2 - 4). Please draft your plan for the next semester.
Thank you page (1- 2). Thank yourself and your team for this work.

**Comment by BlazingEmerald** [comment]
Completed, Along with The demo presentarion.
